version: "1.0.0"

services:
  frontend:
    container_name: fontend-ui
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - messenger
    networks:
      - whisper-network

  messenger:
    build: ./messenger
    container_name: messenger
    env_file:
      - ./messenger/.env
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./credentials/google.api.json
    networks:
      - whisper-network

  mongodb:
    image: mongo
    container_name: mongo-login-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - whisper-network

  pinecone:
    build: ./pinecone
    container_name: pinecone-vector-db
    ports:
      - "4000:4000"
    networks:
      - whisper-network

volumes:
  mongo-data:
  redis-data:

networks:
  whisper-network:
    driver: bridge
