version: "1.0.0"

services:
  whisper-backend:
    build: ./backend
    container_name: whisper-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./credentials/google.api.json
      
  whisper-frontend:
    container_name: whisper-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - whisper-backend
    networks:
      - whisper-network
networks:
  whisper-network:
    driver: bridge
