version: "1.0.0"

services:
  mongodb-login:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    networks:
      - whisper-network

  redis-cache:
    image: redis
    restart: always
    container_name: redis
    expose:
      - 6379
    networks:
      - whisper-network

  backend:
    build: ./backend
    container_name: node-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./credentials/google.api.json
    networks:
      - whisper-network

  frontend:
    container_name: react-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge
